name: 'Setup Python Environment'
description: 'Sets up Python with specified version and installs packages'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  packages:
    description: 'Space-separated list of pip packages to install'
    required: false
    default: 'requests'

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install ${{ inputs.packages }}
